# Generated by Django 2.1 on 2018-08-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'In Queue'), ('1', 'Run'), ('2', 'Completed')], max_length=1, null=True)),
                ('create_time', models.TimeField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('time_to_execute', models.FloatField(null=True)),
            ],
        ),
    ]
